import { Metadata } from "next";
import HomePage from "./(public)/home/page";

export const metadata: Metadata = {
  title: "Yunolabs Evaluation Excercise",
  description: "Generated by create next app",
  keywords: "create next",
};

export default function Home() {
  return (
    <>
      <HomePage />
    </>
  );
}
